# Use root/example as user/password credentials
version: '3.8'

services:

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: sktmelovision
        ports:
            - "45678:45678"
        volumes:
            - ./mongodata:/data/db
        networks:
            - my_network

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "56789:56789"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: sktmelovision
            ME_CONFIG_MONGODB_URL: mongodb://root:sktmelovision@mongo:45678/
        networks:
            - my_network

    api:
        build:
            context: ./
            dockerfile: Dockerfile.api
        restart: always
        ports:
            - "34567:34567"
        networks:
            - my_network

networks:
    my_network:
        driver: bridge