# Use root/example as user/password credentials
version: '3.3'

services:

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: sktmelovision
        volumes:
            - ./mongodata:/data/db
        networks:
            - my_network

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            VCAP_APP_HOST: mongo-express
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: sktmelovision
            ME_CONFIG_BASICAUTH_USERNAME: melovision
            ME_CONFIG_BASICAUTH_PASSWORD: sktmelovision
            ME_CONFIG_MONGODB_SERVER: mongo
        ports:
            - "8081:8081"
        networks:
            - my_network

    api:
        build:
            context: ./
            dockerfile: Dockerfile.api
        restart: always
        networks:
            - my_network

    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../nginx/.htpasswd:/etc/nginx/.htpasswd
        networks:
            - my_network

networks:
    my_network:
        driver: bridge